name: バグ報告
description: 改善のために報告を作成してください
title: "[BUG]: "
labels: ["bug", "enhancement"]
assignees: 'KUN1007'

body:
  - type: markdown
    attributes:
      value: |
        **バグの説明**
        バグの内容を明確かつ簡潔に説明してください。

        **再現手順**
        問題を再現する手順：

        1. 「...」に移動
        2. 「....」をクリック
        3. 「....」までスクロール
        4. エラーを確認

        **期待される動作**
        発生が期待される動作を明確かつ簡潔に説明してください。

        **スクリーンショット**
        該当する場合は、問題を説明するためにスクリーンショットを追加してください。

        **追加情報**
        問題に関するその他の情報をここに追加してください。
