name: 错误报告
description: 创建错误报告以帮助我们改进
title: "[错误]: "
labels: ["错误", "增强"]
assignees: 'KUN1007'

body:
  - type: markdown
    attributes:
      value: |
        **描述错误**
        清晰简洁地描述错误是什么。

        **重现步骤**
        重现问题的步骤：

        1. 转到 '...'
        2. 点击 '....'
        3. 滚动到 '....'
        4. 看到错误

        **预期行为**
        清晰简洁地描述您期望发生的情况。

        **截图**
        如果适用，请添加截图以帮助解释您的问题。

        **其他上下文**
        在此处添加有关问题的其他上下文。
