name: 功能请求
description: 建议一个想法或增强功能
title: "[功能请求]: "
labels: ["增强功能"]
assignees: 'KUN1007'

body:
  - type: markdown
    attributes:
      value: |
        **您的功能请求是否与某个问题相关？请描述。**
        清楚且简洁地描述问题或需求。例如：每当 [...] 时，我总是感到很困扰。

        **描述您想要的解决方案**
        清楚且简洁地描述您预期发生的事情。

        **描述您考虑过的替代方案**
        清楚且简洁地描述您考虑过的任何替代解决方案或功能。

        **其他上下文**
        在这里添加有关功能请求的其他上下文或截图。